AWSTemplateFormatVersion: "2010-09-09"
Description: ACM certificates for CloudFront (us-east-1)

Resources:
  # {% if domain %}
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "{{ domain }}"
      DomainValidationOptions:
        - DomainName: "{{ domain }}"
          HostedZoneId: "{{ hosted_zone_id }}"
      Tags:
        - Key: Name
          Value: "{{ resource_prefix }}cloudfront-cert"
      ValidationMethod: DNS
  # {% endif %}

  # {% for rf in redirect_from %}
  "Certificate{{ rf.yaml_key }}":
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "{{ rf.domain }}"
      DomainValidationOptions:
        - DomainName: "{{ rf.domain }}"
          HostedZoneId: "{{ hosted_zone_id }}"
      Tags:
        - Key: Name
          Value: "{{ resource_prefix }}spa-cert-{{ rf.yaml_key }}"
      ValidationMethod: DNS
  # {% endfor %}

Outputs:
  # {% if domain %}
  CertificateArn:
    Value:
      Ref: Certificate
  # {% endif %}
  # {% for rf in redirect_from %}
  "CertificateArn{{ rf.yaml_key }}":
    Value:
      Ref: "Certificate{{ rf.yaml_key }}"
  # {% endfor %}
