kits = ["core", "vmgit", "uv", "just", "postgres", "docker", "infra", "claude", "mysql", "redis", "depot", "rust"]
aws_region = "ap-northeast-1"

[[mounts]]
type = "overlay"
path = ".git"
is_file = "auto"
managed = "forge"

[[mounts]]
type = "overlay"
path = ".venv"
managed = "uv"

[[mounts]]
type = "overlay"
path = "node_modules"
managed = "bun"

[[mounts]]
type = "overlay"
path = "example-tidb/.venv"

[[mounts]]
type = "overlay"
path = "example-neon/.venv"
[[mounts]]
type = "overlay"
path = ".forge/workspace"
managed = "forge"
[[mounts]]
type = "overlay"
path = "target"
managed = "rust"
[[mounts]]
type = "inject"
source = ".forge/vm/.claude/settings.local.json"
target = ".claude/settings.local.json"
is_file = true
managed = "claude"
