AWSTemplateFormatVersion: "2010-09-09"
Description: spa configuration for webapp

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - Certificate
    Properties:
      DistributionConfig:
        Aliases:
          - "{{ domain }}"
        Enabled: true
        Origins:
          - Id: "{{ origin_id }}"
            DomainName:
              Fn::Sub: "{{ bucket_name }}.s3.${AWS::Region}.amazonaws.com"
            # OriginPath: "" ##### stage info should be here, after change bucket name #####
            S3OriginConfig:
              OriginAccessIdentity: "" # Leave this blank because we use OAC(Origin Access Control)
        DefaultCacheBehavior:
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6" # Managed-CachingOptimized
          TargetOriginId: "{{ origin_id }}"
          ViewerProtocolPolicy: "redirect-to-https"
        ViewerCertificate:
          AcmCertificateArn:
            Ref: Certificate
          SslSupportMethod: sni-only

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "{{ domain }}"
      DomainValidationOptions:
        - DomainName: "{{ domain }}"
          HostedZoneId: "{{ hosted_zone_id }}"
      Tags:
        - Key: Name
          Value: "{{ slug }}-spa-cert"
      ValidationMethod: DNS

  DNSRecord:
    Type: AWS::Route53::RecordSet
    DependsOn:
      - CloudFrontDistribution
    Properties:
      HostedZoneId: "{{ hosted_zone_id }}"
      Name: "{{ domain }}"
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # Z2FDTNDATAQYW2 is the fixed hosted zone id for cloudfront
        DNSName:
          Fn::GetAtt: CloudFrontDistribution.DomainName

Outputs:
  DistributionId:
    Value:
      Ref: CloudFrontDistribution
