# magic-pocket-cli generator version: 0.13.0
[general]
region = "ap-northeast-1"
stages = ["dev", "sandbox"]
project_name = "pocket-example-neon"

[neon]
project_name = "dev-magic-pocket"
provisioning = "command"

[sandbox.neon]
project_name = "dev-magic-pocket"
branch_name = "sandbox"

[sandbox.cloudfront]

[sandbox.cloudfront.web]
domain = "neon.sandbox.magic-pocket.example.com"
routes = [
    { type = "lambda", handler = "wsgi", is_default = true },
    { path_pattern = "/static/*", ref = "static", versioning = "deploy_hash", origin_path = "/static" },
]

[s3]


[awscontainer]
dockerfile_path = "__runtime__"

[awscontainer.handlers.wsgi]
command = "pocket.django.lambda_handlers.wsgi_handler"

[awscontainer.handlers.wsgi.apigateway]


[awscontainer.handlers.management]
command = "pocket.django.lambda_handlers.management_command_handler"
timeout = 600

[awscontainer.django.storages]

[awscontainer.django.storages.default]
store = "filesystem"

[awscontainer.django.storages.staticfiles]
store = "s3"
static = true
distribution = "web"
route = "static"

[awscontainer.secrets]
store = "ssm"

[awscontainer.secrets.managed.SECRET_KEY]
type = "password"

[awscontainer.secrets.managed.SECRET_KEY.options]
length = 50

[awscontainer.secrets.managed.DJANGO_SUPERUSER_PASSWORD]
type = "password"

[awscontainer.secrets.managed.DJANGO_SUPERUSER_PASSWORD.options]
length = 16

[awscontainer.secrets.user.DATABASE_URL]
type = "neon_database_url"
